#include "spells.h"

#define SpellIndex(n) IDInd(Spell_##n##)

u8 SpellList[]={
    SpellIndex(Immolation),
    SpellIndex(Escape),
    SpellIndex(RemovePoison),
    SpellIndex(AirShield),
    SpellIndex(ControlElem),
    SpellIndex(Debilitation),
    SpellIndex(DragonFlames),
    SpellIndex(EarthSmite),
    SpellIndex(Fireball),
    SpellIndex(Lightning),
    SpellIndex(Strength),
    SpellIndex(Wind),
    SpellIndex(Teleportation),
    SpellIndex(Brilliance),
    SpellIndex(Stupidity),
    SpellIndex(Banishing),
    SpellIndex(Charming),
    SpellIndex(ControlMarquis),
    SpellIndex(DetectingTraps),
    SpellIndex(Endurance),
    SpellIndex(Opening),
    SpellIndex(SenseAura),
    SpellIndex(Weakness),
    SpellIndex(CheatDeath),
    SpellIndex(AcidBolt),
    SpellIndex(AuraOfDeath),
    SpellIndex(WraithTouch),
    SpellIndex(ControlZombies),
    SpellIndex(CrushingDeath),
    SpellIndex(Darkness),
    SpellIndex(Haste),
    SpellIndex(Exhaustion),
    SpellIndex(Stamina),
    SpellIndex(TapStamina),
    SpellIndex(WallOfBones),
    SpellIndex(SpiritShield),
    SpellIndex(Poison),
    SpellIndex(Mirror),
    SpellIndex(VsElemental),
    SpellIndex(VsNaming),
    SpellIndex(VsNecromancy),
    SpellIndex(VsStar),
    SpellIndex(DispelElemental),
    SpellIndex(DispelNaming),
    SpellIndex(DispelNecromancy),
    SpellIndex(DispelStar),
    SpellIndex(Photosynthesis),
    SpellIndex(SolarWrath),
    SpellIndex(StarlightShield),
    SpellIndex(DetectMoonPhase),
    SpellIndex(DetectSunPhase),
    SpellIndex(Dexterity),
    SpellIndex(Clumsiness),
    SpellIndex(FrozenDoom),
    SpellIndex(Light),
    SpellIndex(Stealth),
    SpellIndex(StellarGravity),
    SpellIndex(WebOfStarlight),
    SpellIndex(WhiteFire),
    0,0,0,0,0//likely align bytes.
};